INSERT INTO Performer_Details  VALUES ('Paul', 'Smith', 'Lead Vocals');
INSERT INTO Performer_Details VALUES ('Dan', 'Smath', 'Lead Guitar');
INSERT INTO Performer_Details VALUES ('Alex', 'Boxman', 'Singer');
INSERT INTO Performer_Details VALUES ('Dan', 'Cueton', 'Pianist');
INSERT INTO Performer_Details VALUES ('Patrick', 'Croft', 'Guitar');
INSERT INTO Performer_Details VALUES ('Dave', 'Yau', 'Bass');
INSERT INTO Performer_Details  VALUES ('Sam', 'Burton', 'Pianist ');
INSERT INTO Performer_Details VALUES ('Harry', 'Cambridge', 'DJ');
INSERT INTO Performer_Details VALUES ('Paul', 'Stafford', 'Singer');
INSERT INTO Performer_Details VALUES ('Bill', 'Cave', 'Vocals');
INSERT INTO Performer_Details VALUES ('Ronnie', 'Green', 'Violin');
INSERT INTO Performer_Details VALUES ('George', 'Blue', 'Pianist');
